# tenzro-node as a fully sandboxed systemd unit (docs/03-ARCHITECTURE.md §6).
#
# No `tenzro join --provider`, no wallet, no earnings: the identity agent
# (docs/03-ARCHITECTURE.md §4.4) owns those and it doesn't exist yet. Faking
# them would create migration debt. Disabled by default; only enable once the
# update/rollback machinery is proven green in CI.
{ config, lib, pkgs, ... }:
let
  cfg = config.sovox.tenzro;
in
{
  options.sovox.tenzro = {
    enable = lib.mkEnableOption "tenzro-node (CPU variant only — the CUDA overlay matrix is v0.1)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ./package.nix { };
      defaultText = lib.literalExpression "pkgs.callPackage ./package.nix { }";
      description = "Pinned tenzro-node derivation (upstream release binary or Rust workspace build).";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra lines appended to /etc/tenzro/node.toml.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Network contract: 9000/tcp+udp appended to baseline (dedup'd by
    # hardening/base.nix); RPC surfaces are loopback by construction — no
    # firewall rule can re-expose what never binds a routable address.
    sovox.internal.baselinePorts = [ 9000 ];

    environment.etc."tenzro/node.toml".text = ''
      # Generated by modules/tenzro (prototype). Loopback RPC by construction.
      [network]
      listen = "0.0.0.0:9000"

      [rpc]
      ethereum = "127.0.0.1:8545"
      web_api = "127.0.0.1:8080"
      mcp = "127.0.0.1:3001"
      a2a = "127.0.0.1:3002"

      [storage]
      # StateDirectory=tenzro → /var/lib/tenzro, backed by
      # rpool/safe/state/tenzro (recordsize=16K, fsync honored).
      data_dir = "/var/lib/tenzro"
    '' + cfg.extraConfig;

    # Unit hardening exactly per Arch §6.
    systemd.services.tenzro-node = {
      description = "Tenzro Network node";
      wantedBy = [ "multi-user.target" ];
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      restartTriggers = [ config.environment.etc."tenzro/node.toml".source ];
      serviceConfig = {
        ExecStart = "${cfg.package}/bin/tenzro-node --config /etc/tenzro/node.toml";
        Restart = "on-failure";
        RestartSec = 5;

        DynamicUser = true;
        StateDirectory = "tenzro";
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictNamespaces = true;
        LockPersonality = true;
        RestrictRealtime = true;
        SystemCallFilter = [ "@system-service" "~@privileged" ];
        RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];

        # cgroup weights: the node yields to interactive/system work
        CPUWeight = 90;
        IOWeight = 90;
      };
    };

    # /var/lib/tenzro persists across the impermanent root; on real disks it
    # is the dedicated dataset from images/disko/*.nix.
    environment.persistence."/persist".directories =
      lib.mkIf config.sovox.internal.impermanence.enable [ "/var/lib/tenzro" ];
  };
}
